// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// This is a code

const SUPABASE_URL = "https://tssbfvquiwjlvhehvxpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzc2JmdnF1aXdqbHZoZWh2eHBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0MjE5MTAsImV4cCI6MjA3Nzk5NzkxMH0.Qj5JB--kjmeOw7qFPT3EEfI8U5nMBnEnGW4AIj33fw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});